Dockerfile
pages/problems/[problemId].tsx

- add: 回答は20分に一度のみという情報を追加し付属する env を追加

add: 回答は20分に一度のみという情報を追加し付属する env を追加

---

components/MarkdownPreview.tsx
package.json
pages/_app.tsx
pages/index.tsx
yarn.lock

add: Mermaid 記法に対応

---

pages/problems/[problemId].tsx
pages/scoring/index.tsx
types/Problem.ts

- fix: problem の body が undefined の場合があるので対応

fix: problem の body が undefined の場合があるので対応

---

hooks/problem.ts
package.json
pages/problems/[problemId].tsx
pages/scoring/[code].tsx
pages/scoring/index.tsx
styles/globals.css
types/Problem.ts
yarn.lock

update: Matter が対応できる様に機能追加

---

components/ProblemCard.tsx
types/Problem.ts

update: 点数を一覧から確認できるようになった

---

components/HoverCopyText.tsx
pages/problems/[problemId].tsx

update: 問題詳細にてコピー機能を実装

---

pages/signup.tsx

fix: signUp から signup に変更

---

components/Navbar.tsx
pages/team_info.tsx
types/UserGroup.ts

update: チーム情報ページを追加

---

pages/team_info.tsx

- update: チーム情報ページに得点と順位とメンバーを追加

update: チーム情報ページに得点と順位とメンバーを追加

---

pages/team_info.tsx

- update: Copy ボタンを押したときに下の IP を隠す機能も動いてしまっていたのを修正

update: Copy ボタンを押したときに下の IP を隠す機能も動いてしまっていたのを修正

---

pages/problems/index.tsx

closed #62 
- update: 問題一覧ページで幅を小さくすると列の量を減らすようにした

update: 問題一覧ページで幅を小さくすると列の量を減らすようにした

---

pages/problems/[problemId].tsx

* fix: リロードすると一瞬 404 が表示されるのを修正

fix: 問題ページでリロードすると一瞬 404 が表示されるのを修正

---

pages/team_info.tsx

fix: 接続情報から踏み台サーバへの接続情報へ変更

---

components/Navbar.tsx

fix: NavBar の自分の情報を表示するドロップダウンの色が透明になっていたのを白に修正

---

pages/team_info.tsx

update: Hidden ボタンを追加

---

pages/team_info.tsx

update: hidden を input で実装

---

pages/team_info.tsx

update: チーム情報ページのメンバー一覧を削除

---

pages/problems/index.tsx

update: 短いルールを問題一覧に持って来れるようにした

---

pages/problems/[problemId].tsx
pages/scoring/[code].tsx

採点画面でも同様に問題コードが表示されるようにした。あとタイトルにも追加した。

use problem code instead of index (again)

---

pages/scoring/[code].tsx

update: 未採点をデフォルトに

---

pages/problems/[problemId].tsx

add answer download button

---

layouts/BaseLayout.tsx
pages/index.tsx
pages/login.tsx
pages/notices.tsx
pages/problems/[problemId].tsx
pages/problems/index.tsx
pages/profile.tsx
pages/ranking.tsx
pages/scoring/[code].tsx
pages/scoring/index.tsx
pages/signup.tsx
pages/team_info.tsx
pages/users.tsx
tsconfig.json

- import エイリアエスを使用するように
- BaseLayout を使用するようにすべてのページをリファクタリング

refactor: BaseLayout を使用するようにすべてのページをリファクタリング

---

pages/ranking.tsx

#143 の修正。手元で動かした感じ、挙動に問題はなくちゃんとスクロールできました。

scroll ranking

---

.eslintrc.json
README.md
components/Navbar.tsx
hooks/answer.ts
hooks/api.ts
hooks/auth.test.ts
hooks/auth.ts
hooks/notice.ts
hooks/problem.ts
hooks/ranking.ts
hooks/reCreateInfo.ts
hooks/userGroups.tsx
jest.config.mjs
package.json
pages/index.tsx
pages/login.tsx
pages/problems/[problemId].tsx
pages/profile.tsx
pages/scoring/[code].tsx
pages/signup.tsx
types/User.ts
yarn.lock

*add: テストを追加
* update: axios 変更に伴い json でラップするのを削除
* fix: format

テスト基盤を追加および API クライアントを `ky` から `axios` に変更

---

components/Navbar.tsx
hooks/answer.ts
hooks/api.ts
hooks/auth.test.ts
hooks/auth.ts
hooks/notice.ts
hooks/problem.ts
hooks/ranking.ts
hooks/reCreateInfo.ts
hooks/userGroups.tsx
pages/index.tsx
pages/login.tsx
pages/problems/[problemId].tsx
pages/profile.tsx
pages/scoring/[code].tsx
pages/signup.tsx
types/User.ts

* update: apiClient -> client に変更

update: apiClient -> client に変更

---

__test__/components/Navbar.test.tsx
components/Navbar.tsx
hooks/auth.ts
package.json
types/User.ts
yarn.lock

add: ICTSCNavBar のテストを追加

---

.eslintrc.json
__e2e__/index.test.ts
__e2e__/navbar.test.ts
__e2e__/pages/Index.ts
__e2e__/pages/login.ts
__e2e__/pages/navbar.ts
__e2e__/pages/page.ts
__e2e__/pages/problems.ts
__e2e__/pages/profile.ts
__e2e__/pages/ranking.ts
__e2e__/pages/scoring.ts
__e2e__/pages/teamInfo.ts
__e2e__/pages/users.ts
__test__/components/Navbar.test.tsx
components/Navbar.tsx
hooks/api.ts
hooks/auth.ts
layouts/CommonLayout.tsx
package.json
pages/login.tsx
pages/problems/[problemId].tsx
pages/profile.tsx
pages/signup.tsx
playwright.config.ts
vitest.config.ts
yarn.lock

* add: playwright を導入
* add: index と navbar のテストを追加

add: playwright を導入 / add: index と navbar のテストを追加

---

__test__/hooks/problem.test.ts
__test__/hooks/problems.test.ts
hooks/problem.ts
hooks/problems.ts
types/Problem.ts

add: Problem の hooks テストを追加

---

__test__/hooks/answer.test.ts
hooks/answer.ts
types/Answer.tsx
types/User.ts
types/UserGroup.ts
types/_api.ts

add: Answer の hooks テストを追加

---

__test__/hooks/notice.test.ts
hooks/notice.ts
types/Notice.ts

add: notice の hooks テストを追加

---

__test__/hooks/ranking.test.ts
hooks/ranking.ts
types/Rank.ts
types/_api.ts

add: ranking の hooks テストを追加

---

__test__/hooks/reCreateInfo.test.ts
hooks/reCreateInfo.ts
types/ReCreate.ts

* add: ReCreateInfo の hooks テストを追加

add: ReCreateInfo の hooks テストを追加

---

__test__/pages/signup.test.tsx
hooks/auth.ts
pages/signup.tsx
types/_api.ts

add: SignUpPage の単体テストを追加

---

__test__/hooks/problem.test.ts
__test__/pages/problems/index.test.tsx
__test__/pages/signup.test.tsx
components/LoadingPage.tsx
components/_const.ts
pages/problems/index.tsx
types/Notice.ts
types/Problem.ts

* add: ProblemIndex の 単体 テストを追加

add: ProblemIndex の 単体 テストを追加

---

__test__/pages/problems/[problemId].test.tsx
__test__/pages/problems/index.test.tsx
components/AnswerForm.tsx
components/AnswerListSection.tsx
components/_const.ts
hooks/reCreateInfo.ts
pages/problems/[problemId].tsx

* add: ProblemPage の 単体 テストを追加

add: ProblemPage の 単体 テストを追加

---

__test__/pages/scoring/[code].test.tsx
__test__/pages/scoring/index.test.tsx
components/ScoringAnswerForm.tsx
pages/scoring/[code].tsx
types/Answer.tsx

* add: ScoringProblemPage の 単体 テストを追加

add: ScoringProblemPage の 単体 テストを追加

---

__test__/pages/notices.test.tsx

* add: NoticesPage の 単体 テストを追加

add: NoticesPage の 単体 テストを追加
